"""
This script is used under the project "Omnigraph"

Input:
    1- Fasta file of the cDBG unitigs
    2- collectiveComps.csv (Generated by the script unitigs_to_connected_components.py)

Output:
    1- Names TSV ready to be used by the kmersColoring executable

Run:
    - python unitigs_to_names_tsv.py <unitigs_fasta> <connected_components_tsv>

Example:
    - python unitigs_to_names_tsv.py unitigs.fa unitigs.fa.components.tsv

"""

import sys
import os
import subprocess
from tqdm import tqdm

if len(sys.argv) < 3:
    sys.exit("run: python unitigs_to_names_tsv.py <unitigs_fasta> <connected_components_tsv>")

unitigs_fasta = sys.argv[1]
connected_components_tsv = sys.argv[2]

originalCompsNo = int(subprocess.getoutput(f"wc -l {connected_components_tsv}").split()[0])
no_seqs = int(subprocess.getoutput('wc -l ' + unitigs_fasta).split()[0]) // 2

print(f"Number of components: {originalCompsNo}")

namesTSV_file = os.path.basename(unitigs_fasta) + ".names.tsv"

print("Mapping unitigs components ...", file=sys.stderr)

unitig_to_component = dict()
# component_to_unitigs = dict()

with open(connected_components_tsv, 'r') as compsReader:
    for line in tqdm(compsReader, total=originalCompsNo):
        line = line.strip().split(',')
        compID = line[0]
        # component_to_unitigs[compID] = list()

        for unitig in line[1:]:
            unitig_to_component[unitig] = compID
            # component_to_unitigs[compID].append(unitig)

print(f"Writing {namesTSV_file} ...", file=sys.stderr)
with open(unitigs_fasta, 'r') as unitigsReader, open(namesTSV_file, 'w') as names_tsv_Writer:
    for line in tqdm(unitigsReader, total=no_seqs):
        seq_len = len(next(unitigsReader).strip())
        header = line.strip().split()
        unitig_id = header[0][1:]
        names_tsv_Writer.write(f"{unitig_id}\t{unitig_to_component[unitig_id]}\n")
